# Generated by Django 4.1.3 on 2022-11-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinsa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testee',
            name='eighth_grade',
            field=models.DateField(blank=True, null=True, verbose_name='八段取得日(yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='testee',
            name='hanshi',
            field=models.DateField(blank=True, null=True, verbose_name='範士取得日(yyyy-mm-dd)'),
        ),
    ]
