version: '3'

services:
  web:
    build: .
    tty: true
    volumes:
      - ../:/workspace
    depends_on:
      - db

  db:
    image: postgres
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: mjer
        POSTGRES_PASSWORD: 1muso2jikiden
        POSTGRES_DB: mjerapp

  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: info.mjer@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 1muso2jikiden
    depends_on:
      - db

volumes:
    postgres_data:
    pgadmin4_data: